[package]
name = "ci-bin"
version.workspace = true
edition.workspace = true
publish = false
rust-version.workspace = true

[features]
default = ["std"]
std = ["alloc", "ci-lib/std"]
alloc = ["ci-lib/alloc"]

[dependencies]
ci-lib = { workspace = true, default-features = false }
