[workspace]
resolver = "3"
members = ["ci-bin", "ci-lib"]

[workspace.package]
edition = "2024"
rust-version = "1.85"

[workspace.dependencies]
ci-lib = { path = "./ci-lib", default-features = false, version = "=0.1.0" }
