name: check
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read
defaults:
  run:
    shell: bash
env:
  # needed for cargo-insta and other tools
  CI: "true"
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings
  MAIN_CRATE: "ci-lib"
jobs:
  fmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1.15.2
      - name: cargo fmt
        run: cargo fmt --check --all
  clippy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/install-deps
      - uses: actions-rust-lang/setup-rust-toolchain@v1.15.2
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: cargo clippy
        run: cargo clippy --locked --all-targets --all-features --workspace

  cross:
    runs-on: ubuntu-24.04
    # use Debian to add other architectures
    container: debian:13.2
    name: cross / ${{ matrix.target.rust }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - rust: aarch64-unknown-linux-gnu
            deb: arm64
            toolchain: gcc-aarch64-linux-gnu
          - rust: aarch64-unknown-linux-musl
            deb: arm64
            toolchain: gcc-aarch64-linux-gnu
    env:
      DEBIAN_FRONTEND: noninteractive
      CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER: aarch64-linux-gnu-gcc
      CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
    steps:
      - name: install toolchain and deps
        run: |
          dpkg --add-architecture ${{ matrix.target.deb }}
          apt-get update
          apt-get install -y curl git build-essential ${{ matrix.target.toolchain }}
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/install-deps
      - uses: actions-rust-lang/setup-rust-toolchain@v1.15.2
        with:
          target: ${{ matrix.target.rust }}
      - run: |
          echo '. "$HOME/.cargo/env"' >> ~/.bashrc
          echo '. "$HOME/.cargo/env"' >> ~/.profile
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: cargo build cross
        run: |
          cargo build --workspace --all-features --target ${{ matrix.target.rust }}

  doc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/install-deps
      - uses: actions-rust-lang/setup-rust-toolchain@v1.15.2
        with:
          toolchain: nightly
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: Install cargo-docs-rs
        uses: dtolnay/install@cargo-docs-rs
      - run: |
          cargo docs-rs --locked -p "$MAIN_CRATE"
  minimal-versions:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/install-deps
      - name: install rust stable
        uses: actions-rust-lang/setup-rust-toolchain@v1.15.2
      - name: install rust nightly
        uses: actions-rust-lang/setup-rust-toolchain@v1.15.2
        with:
          toolchain: nightly
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: taiki-e/install-action@v2.63.3
        with:
          tool: cargo-hack,cargo-minimal-versions
      - run: rustup default stable
      - name: Check minimal versions
        run: cargo minimal-versions check --workspace --ignore-private --detach-path-deps=skip-exact --direct
  msrv:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        msrv: [1.85] # 2021 edition requires 1.85
    name: msrv / ${{ matrix.msrv }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/install-deps
      - uses: actions-rust-lang/setup-rust-toolchain@v1.15.2
        with:
          toolchain: ${{ matrix.msrv }}
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: taiki-e/install-action@v2.63.3
        with:
          tool: cargo-hack
      - name: cargo +${{ matrix.msrv }} check
        run: cargo +${{ matrix.msrv }} hack --no-dev-deps check --all-features -p "$MAIN_CRATE"
  # Run semver-check on release branch push or PR
  semver:
    if: startsWith(github.base_ref, 'release-') || startsWith(github.ref, 'release-')
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1.15.2
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: Check library API semver breakages
        uses: obi1kenobi/cargo-semver-checks-action@v2.8
        with:
          release-type: patch
  # Check that the create can be compiled with only the packaged files
  for-publish:
    name: stable / for-publish
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: ./.github/actions/install-deps
      - uses: actions-rust-lang/setup-rust-toolchain@v1.15.2
      - uses: mozilla-actions/sccache-action@v0.0.9
      - run: ./scripts/ci/check-for-publish.sh
